### ISSUE TITLE
clearly indicate to users where they should file bugs for operational issues

### ISSUE THREAD

**Issue by wallrj** [twisted-infra/trac-config#1]
Copied from https://bugs.launchpad.net/twisted-website/+bug/1140776

Right now the only thing on the web site suggesting a way to report a problem - with Twisted, with the web site, with the software itself - is the "new ticket" link in the navbar. The fact that one should use the Twisted website for reporting issues with the Twisted website is further reinforced by the presence of the open "website" component. 

As per this discussion: http://twistedmatrix.com/trac/ticket/6329?#comment:5 we should really indicate that issues with Trac-as-deployed should be in github:twisted-infra.

Also, the website component should be closed so that folks don't file new bugs in it.

**Comment by wallrj** [comment]
I drafted some words for inclusion on the new ticket and attachment upload pages.
- https://twistedmatrix.com/trac/wiki/users/rwall/DraftNewTicketPage

**Comment by adiroiban** [comment]
moved to https://github.com/twisted-infra/braid/issues/130
