### ISSUE TITLE
Tickets cannot be unassigned

### ISSUE THREAD

**Issue by exarkun** [twisted-infra/trac-config#14]
There is no longer an empty entry in the "assign to" dropdown on the ticket metadata form.  This seems to make it impossible to make a ticket owned by no one.  This breaks the ticket workflow (which is for tickets up for review to be assigned to no one).

**Comment by adiroiban** [comment]
Maybe this can be solved by adding an empty `<option></option>` in the template.

**Comment by glyph** [comment]
We fixed this, and it broke again because I ran `delete-useless-users` to get rid of a bunch of spammer accounts.  The "empty assignee" account is considered useless by this script, I guess, and for that matter why wouldn't it be :).

**Comment by glyph** [comment]
Scrounging around in trac's completion history for both bash and psql, the magical line to fix this seems to be `insert into session values ('', 0, extract(epoch from current_timestamp));`.  I'll run it again manually now, and perhaps we should add this to `delete-useless-users.py` in the future.

**Comment by glyph** [comment]
Oops, that was actually the wrong thing.

The _correct_ incantation was:

```
trac=> BEGIN;
BEGIN
trac=> INSERT INTO permission VALUES (' ', 'TICKET_MODIFY');
INSERT 0 1
trac=> INSERT INTO session VALUES (' ', 1, extract(epoch from current_timestamp));
INSERT 0 1
trac=> commit;
COMMIT
trac=> 
```

and we can un-assign tickets again.

**Comment by glyph** [comment]
I have filed the bug on delete-useless-users [here](https://bugs.launchpad.net/twisted-trac-integration/+bug/1419200).

**Comment by glyph** [comment]
Since unassignment is back up and running I'm closing.  Please re-open if necessary.

**Comment by adiroiban** [comment]
twisted-trac-integration on Launchad ?

Can I help with moving all that stuff in trac-config?

Twisted Trac / Twisted on GitHub / Twisted-Info on GitHub and then  twisted-trac-integration on Launchad ... I don't know how to chew all this stuff :(

**Comment by glyph** [comment]
Already in the plan: https://bugs.launchpad.net/twisted-trac-integration/+bug/1312424

https://github.com/termie/lp2gh is a good place to start.

**Comment by tomprince** [comment]
The most of the stuff remaining in twisted-trac-integration probably doesn't actually want to be in trac-config (except maybe the weekly bug report script). That repo has/had a bunch of stuff, some which has already been migrated (and I think that everything that has has been deleted. It still contains the svn-hooks, for example.

**Comment by adiroiban** [comment]
I have crated a dedicated ticket to discuss and finalize the migration  #22
