### ISSUE TITLE
Fix post commit hook when saving trac ticket changes

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/trac-config#20]
I see this the log

I think that in some cases cnum is int instead of string... will investigate

```
+ /svn/Twisted/hooks/trac-post-commit-pb-client 43738 adiroiban 'Branching to core-test-names-7666.' twistedmatrix.com 38159
2015-01-24 10:27:36-0700 [-] Log opened.
2015-01-24 10:27:36-0700 [-] Starting factory <twisted.spread.pb.PBClientFactory instance at 0x8ccaf2c>
2015-01-24 10:27:37-0700 [Broker,client] postCommit result Traceback (most recent call last):
2015-01-24 10:27:37-0700 [Broker,client]   File "/srv/trac/config/trac-post-commit-hook", line 188, in __init__
2015-01-24 10:27:37-0700 [Broker,client]     ticket.save_changes(self.author, self.msg, self.now, db, cnum+1)
2015-01-24 10:27:37-0700 [Broker,client]   File "/srv/trac/.local/lib/python2.7/site-packages/trac/ticket/model.py", line 366, in save_changes
2015-01-24 10:27:37-0700 [Broker,client]     return int(cnum.rsplit('.', 1)[-1])
2015-01-24 10:27:37-0700 [Broker,client] AttributeError: 'int' object has no attribute 'rsplit'
2015-01-24 10:27:37-0700 [Broker,client] Unexpected error while processing ticket ID 7666
2015-01-24 10:27:37-0700 [Broker,client] 
2015-01-24 10:27:37-0700 [Broker,client] Stopping factory <twisted.spread.pb.PBClientFactory instance at 0x8ccaf2c>
```

**Comment by adiroiban** [comment]
I see that cnum+1 is no longer used in trac 1.0 and from what I see, we use trac 1.0.1

https://github.com/edgewall/trac/blob/trunk/trac/ticket/model.py#L313

---

so we need to update the trac-post-commit-hook

I think that the latest script is called commit_updated

https://github.com/edgewall/trac/blob/eb4c4b586628b3d1262465cce7474346a213a27a/tracopt/ticket/commit_updater.py

Trac upgrade documentation state

```
Note that if you were using the `trac-post-commit-hook`, ''you're strongly advised to upgrade it'' to the new hook documented in the above references and [TracWorkflow#Howtocombinethetracopt.ticket.commit_updaterwiththetestingworkflow here], as the old hook will not work with anything else than the default repository and even for this case, it won't trigger the appropriate notifications.
```

See full doc here https://twistedmatrix.com/trac/wiki/TracUpgrade

---

So to fix this I think that we should use the new commit hook

What do you think?

**Comment by tomprince** [comment]
[Yes](https://twistedmatrix.com/trac/wiki/Infrastructure/UpgradingTrac)

**Comment by adiroiban** [comment]
OK. So all steps, beside step 5 were done ? I have no idea what is the progress of trac upgrade and how can I help.

Any tips are much appreciated.

Thanks!

**Comment by tomprince** [comment]
> OK. So all steps, beside step 5 were done ?

Unfortunately, I don't know the answer to that question. I wasn't directly involved in the migration. @glyph or @dreid perhaps know.

**Comment by glyph** [comment]
@adiroiban as far as I know, all the steps were done.

However, the Subversion repository is on a different host, so if step 5 (copying static website content!?) is what is supposed to update the post-commit hook, perhaps we need to copy it to a different server.

**Comment by adiroiban** [comment]
On the wiki page linked by Tom Prince, step 5 is
1. Updates post-commit hook.

From what I can see in this repo and errors on svn.twistedmatrix.com the old hook is still used.. the one using cnum... the old hook is also present in this repo.

It needs to be updated with a newer version like https://github.com/edgewall/trac/blob/eb4c4b586628b3d1262465cce7474346a213a27a/tracopt/ticket/commit_updater.py as documented in Trac Upgrade doc  https://twistedmatrix.com/trac/wiki/TracUpgrade

---

I took a look at this repo but could not find out how the hook is copied and where the hook is copied... there are so many repos in twisted-infa project, that I am lost :(

**Comment by tomprince** [comment]
> I took a look at this repo but could not find out how the hook is copied and where the hook is copied... 

The setup of the wolfwood (the vcs server, also known as `svn.twistedmatrix.com` or `code.twistedmatrix.com`) was never automated. The svn hooks live [here](https://bazaar.launchpad.net/~twisted-dev/twisted-trac-integration/trunk/files/head:/svn-hooks/) (in bzr still).

The [post commit hook](https://bazaar.launchpad.net/~twisted-dev/twisted-trac-integration/trunk/view/head:/svn-hooks/post-commit#L100) calls [trac-post-commit-pb-client](https://bazaar.launchpad.net/~twisted-dev/twisted-trac-integration/trunk/view/head:/trac-hooks/trac-post-commit-pb-client). That uses [PB](https://twistedmatrix.com/documents/current/core/howto/pb-usage.html) to talk to a [server](https://github.com/twisted-infra/trac-config/blob/master/postcommit.py) (started [here](https://github.com/twisted-infra/trac-config/blob/master/server.tac#L47-48)) that calls trac's [post-commit hook](https://github.com/twisted-infra/trac-config/blob/master/trac-post-commit-hook). The last is based on the old upstream hook, but customized to add some more fields and recognize the commit format we use.

> there are so many repos in twisted-infa project, that I am lost :(

Sorry about that. When I was writing much of the automation, I think most of the documentation end up more as notes to myself, rather than as something that makes it easy for other people to pick-up. :frowning: Feel free to ask questions, either here or on `#twisted-admin` and I'll answer as I can.

**Comment by adiroiban** [comment]
Thanks for the info. For my point of view I should not about the whole chain based on which trac-post-commit-hook is called. I am happy to know that it is called.

Since this is based on on old version, it needs to be updated.

The git history does not help me https://github.com/twisted-infra/trac-config/commits/master/trac-post-commit-hook

Is there a list with those "more fields" ? Is there any info regarding what is different in Twisted commit format ?

AFAIK twisted uses the standard commit format fixes #1111 / ref #2344 being recognized by the script.

I will try to find the upstream old version and then compare with current one to see what was changed... so that I can apply the same changes on current upstream version.

**Comment by tomprince** [comment]
> The git history does not help me https://github.com/twisted-infra/trac-config/commits/master/trac-post-commit-hook

If the history is not in git, it might be in [bzr](https://code.launchpad.net/~twisted-dev/twisted-trac-integration/trunk). Or maybe not. Before braid existed, not all of twisted's infrastructure was version controlled.

> Is there a list with those "more fields" ? Is there any info regarding what is different in Twisted commit format ?

There is at least the branch and author handling, for new branches.

**Comment by adiroiban** [comment]
I got it http://bazaar.launchpad.net/~twisted-dev/twisted-trac-integration/trunk/view/head:/trac-hooks/trac-post-commit-hook ... but it does not have a great history.

I should be able to find the upstream hook and compare the changes.

Will come back with a patch.

Thanks!

**Comment by adiroiban** [comment]
Made some progress. I think that this is the source... there is also re-open action. https://raw.githubusercontent.com/edgewall/trac/0.11-stable/contrib/trac-post-commit-hook

**Comment by adiroiban** [comment]
moved to https://github.com/twisted-infra/braid/issues/123
