### ISSUE TITLE
use database-backed password storage instead of file-backed

### ISSUE THREAD

**Issue by glyph** [twisted-infra/trac-config#24]
https://trac-hacks.org/wiki/AccountManagerPlugin says we can keep password data in the trac database rather than in a text file.  Given that we keep having this problem where our htaccess file gets overwritten, it would be great to just not have an htaccess file at all.

**Comment by glyph** [comment]
specifically, see https://trac-hacks.org/wiki/CookBook/AccountManagerPluginConfiguration#SessionStore

**Comment by tomprince** [comment]
Note that we currently do auth in twisted.web, which doesn't prevent this, it just needs to be taken into account, and maybe changed.

**Comment by glyph** [comment]
Where does that code live? https://github.com/twisted-infra/trac-config/blob/master/external.py#L35-L45 looks more or less like Trac basic authentication, not twisted.web.

**Comment by tomprince** [comment]
I guess I had faulty memory of how things were set up. I must have been remembering that we did some weird stuff with authentication, which is what you linked to.

**Comment by adiroiban** [comment]
moved to https://github.com/twisted-infra/braid/issues/120
