### ISSUE TITLE
upgrade trac

### ISSUE THREAD

**Issue by glyph** [twisted-infra/trac-config#4]
We are using a super old version of Trac.

There are many issues with it, and with its plugins.

I don't know if upgrading Trac would actually let us address any of those issues directly - commenters on this issue are encouraged to help build up a list of links to those things - but a more recent version would allow us to more productively work with the Trac team to get some of these things addressed.

**Comment by tomprince** [comment]
I made some notes about what would be required to upgrade track:
https://twistedmatrix.com/trac/wiki/Infrastructure/UpgradingTrac

**Comment by exarkun** [comment]
I think you did this.

**Comment by glyph** [comment]
Someone did, that's for sure.
